/**
 * Download the three project fonts as woff2 into apps/web/public/fonts.
 *
 * ARCHITECTURE 1: fonts are self-hosted, no CDN. Two reasons, and the second is the
 * one that matters here. Privacy and offline are the obvious ones. The real one is
 * that text metrics feed CRDT bounds: a text object's height is measured from the
 * rendered glyphs and written into the document. If a font arrives late, or not at
 * all, every client measures a different height for the same text and the board
 * disagrees with itself. A local file that is either present or a build failure is
 * far easier to reason about than a network race.
 *
 * The generated CSS is committed alongside the files, so a normal checkout needs no
 * network. Re-run this only to bump a font version.
 *
 *   node scripts/fetch-fonts.mjs
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = resolve(root, 'apps/web/public/fonts')

// Google's css2 endpoint serves woff2 only to a browser-shaped user agent. Anything
// else gets ttf, which is roughly twice the size for no benefit.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

/**
 * Latin only. The other subsets Google emits (cyrillic, greek, vietnamese) are a
 * further ~120KB per family for glyphs v1 does not promise. Adding one later is a
 * matter of listing it here.
 */
const SUBSETS = ['latin', 'latin-ext']

const FAMILIES = [
  { query: 'Inter:wght@100..900', slug: 'inter' },
  { query: 'JetBrains+Mono:wght@100..800', slug: 'jetbrains-mono' },
  { query: 'Comic+Neue:wght@400;700', slug: 'comic-neue' },
]

/**
 * Split the returned stylesheet into blocks and keep the ones whose preceding
 * comment names a subset we want. The comment is the only place the subset appears;
 * the unicode-range would work too but is far more brittle to match on.
 */
function parseFaces(css) {
  const faces = []
  const blocks = css.split('/*').slice(1)

  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim()
    if (!SUBSETS.includes(subset)) continue

    const url = /src:\s*url\((https:[^)]+\.woff2)\)/.exec(block)?.[1]
    const weight = /font-weight:\s*([^;]+);/.exec(block)?.[1].trim()
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1]
    const style = /font-style:\s*([^;]+);/.exec(block)?.[1].trim() ?? 'normal'
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1].trim()

    if (url === undefined || weight === undefined || family === undefined) continue
    faces.push({ subset, url, weight, family, style, range })
  }

  return faces
}

await mkdir(outDir, { recursive: true })

const rules = []
let downloaded = 0

for (const { query, slug } of FAMILIES) {
  const response = await fetch(`https://fonts.googleapis.com/css2?family=${query}&display=block`, {
    headers: { 'user-agent': UA },
  })
  if (!response.ok) throw new Error(`${query}: css request returned ${response.status}`)

  const faces = parseFaces(await response.text())
  if (faces.length === 0) throw new Error(`${query}: no matching subsets in the response`)

  for (const face of faces) {
    // Weight ranges arrive as "100 900"; flatten so the name is filesystem-safe.
    const suffix = face.weight.replace(/\s+/g, '-')
    const name = `${slug}-${suffix}-${face.subset}.woff2`

    const file = await fetch(face.url, { headers: { 'user-agent': UA } })
    if (!file.ok) throw new Error(`${name}: download returned ${file.status}`)

    const bytes = Buffer.from(await file.arrayBuffer())
    await writeFile(resolve(outDir, name), bytes)
    downloaded += 1
    console.log(`${name}  ${(bytes.length / 1024).toFixed(1)}KB`)

    rules.push(
      [
        '@font-face {',
        `  font-family: '${face.family}';`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        // `block` rather than `swap`. A swap would paint fallback glyphs first and
        // measure them, so the height written to the CRDT would be wrong until the
        // real font landed. A short invisible period is the cheaper failure.
        '  font-display: block;',
        `  src: url('/fonts/${name}') format('woff2');`,
        ...(face.range === undefined ? [] : [`  unicode-range: ${face.range};`]),
        '}',
      ].join('\n'),
    )
  }
}

const header = [
  '/*',
  ' * Generated by scripts/fetch-fonts.mjs. Do not edit by hand.',
  ' *',
  ' * Self-hosted per ARCHITECTURE 1. Imported once from src/styles.css so both the',
  ' * app and the dev harness resolve the same faces.',
  ' */',
  '',
].join('\n')

await writeFile(resolve(outDir, 'fonts.css'), `${header}${rules.join('\n\n')}\n`)
console.log(`\n${downloaded} files, ${rules.length} faces -> apps/web/public/fonts/fonts.css`)
